# Generated by Django 5.0.1 on 2024-01-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fcm_token',
            new_name='token',
        ),
    ]
